name: Actualizador de Supermercados

on:
  schedule:
    # Se ejecuta a las 02:00 AM los días 1 y 15 de cada mes
    - cron: '0 2 1,15 * *'
  workflow_dispatch: # Esto nos crea el botón mágico para probarlo a mano

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código de GitHub
        uses: actions/checkout@v4

      - name: Configurar el entorno de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Playwright y Firebase
        run: |
          pip install playwright firebase-admin
          playwright install chromium

      - name: 🤖 Ejecutar Robot DIA
        run: python actualizar_dia.py || true
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}

      - name: 🤖 Ejecutar Robot Mercadona
        run: python actualizar_mercadona.py || true
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}

      - name: 🤖 Ejecutar Robot Carrefour
        run: python actualizar_carrefour.py || true
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
